// Code generated by ogen, DO NOT EDIT.
package api

type LoginPostRes interface {
	loginPostRes()
}

type RecordsGetRes interface {
	recordsGetRes()
}

type RecordsIDDeleteRes interface {
	recordsIDDeleteRes()
}

type RecordsIDGetRes interface {
	recordsIDGetRes()
}

type RecordsIDPutRes interface {
	recordsIDPutRes()
}

type RegisterPostRes interface {
	registerPostRes()
}
