// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LoginPost implements POST /login operation.
//
// Authenticate user.
//
// POST /login
func (UnimplementedHandler) LoginPost(ctx context.Context, req *UserCredentials) (r LoginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordsGet implements GET /records operation.
//
// Get all user records.
//
// GET /records
func (UnimplementedHandler) RecordsGet(ctx context.Context) (r RecordsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordsIDDelete implements DELETE /records/{id} operation.
//
// Delete record.
//
// DELETE /records/{id}
func (UnimplementedHandler) RecordsIDDelete(ctx context.Context, params RecordsIDDeleteParams) (r RecordsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordsIDGet implements GET /records/{id} operation.
//
// Get specific record.
//
// GET /records/{id}
func (UnimplementedHandler) RecordsIDGet(ctx context.Context, params RecordsIDGetParams) (r RecordsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RecordsIDPut implements PUT /records/{id} operation.
//
// Create or update record.
//
// PUT /records/{id}
func (UnimplementedHandler) RecordsIDPut(ctx context.Context, req *Record, params RecordsIDPutParams) (r RecordsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterPost implements POST /register operation.
//
// Register new user.
//
// POST /register
func (UnimplementedHandler) RegisterPost(ctx context.Context, req *UserCredentials) (r RegisterPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// VersionGet implements GET /version operation.
//
// Get server version.
//
// GET /version
func (UnimplementedHandler) VersionGet(ctx context.Context) (r *VersionInfo, _ error) {
	return r, ht.ErrNotImplemented
}
